Entradas (Inputs):
    Ia, Ib, Ic: Corrientes de las líneas A, B y C, respectivamente.
    Va, Vb, Vc: Voltajes de las líneas A, B y C, respectivamente.

Salidas (Outputs):
    El dataset clasifica los tipos de fallas utilizando una matriz de salida [G C B A], donde los valores binarios indican la ocurrencia de una falla en diferentes fases o con el neutro. Las combinaciones posibles son:
        [0 0 0 0]: Sin falla.                                                                       -> 0
        [1 0 0 1]: Falla entre la fase A y tierra (LG - Línea a tierra).                            -> 1
        [0 0 1 1]: Falla entre las fases A y B (LL - Línea a línea).                                -> 2
        [1 0 1 1]: Falla entre las fases A, B y tierra (LLG - Línea a línea a tierra).              -> 3
        [0 1 1 1]: Falla entre las tres fases (LLL - Línea a línea a línea).                        -> 4
        [1 1 1 1]: Falla trifásica simétrica entre las tres fases y tierra (LLLG - Línea a línea a línea a tierra). -> 5
        otro valor -> 6

In [27]:
# Importar las librerías necesarias
import pandas as pd
import numpy as np

# Ver los archivos
dir_data_validation = 'C:/Users/christianr/Documents/GitHub/EndomorfismoII_2024_2/PROYECTOS/PARCIAL 1/data_valid.csv'
dataset = pd.read_csv(dir_data_validation)
# Matriz de entrada X
X = dataset.drop(columns=['G', 'C', 'B', 'A'])
X.head()
# Matriz de salida 
y = dataset[['G', 'C', 'B', 'A']]
y.head()

G  C  B  A
0  1  0  0  1
1  0  1  1  1
2  0  0  0  0
3  1  0  0  1
4  0  0  1  1

Salidas (Outputs):
    El dataset clasifica los tipos de fallas utilizando una matriz de salida [G C B A], donde los valores binarios indican la ocurrencia de una falla en diferentes fases o con el neutro. Las combinaciones posibles son:
        [0 0 0 0]: Sin falla.                                                                       -> 0
        [1 0 0 1]: Falla entre la fase A y tierra (LG - Línea a tierra).                            -> 1
        [0 0 1 1]: Falla entre las fases A y B (LL - Línea a línea).                                -> 2
        [1 0 1 1]: Falla entre las fases A, B y tierra (LLG - Línea a línea a tierra).              -> 3
        [0 1 1 1]: Falla entre las tres fases (LLL - Línea a línea a línea).                        -> 4
        [1 1 1 1]: Falla trifásica simétrica entre las tres fases y tierra (LLLG - Línea a línea a línea a tierra). -> 5

In [21]:
#Cambiar variable GCBA
y_mat = y.to_numpy()
out = []
for i in range(y_mat.shape[0]):
    if y_mat[i,0] == 0 and y_mat[i,1] == 0 and y_mat[i,2] == 0 and y_mat[i,3] == 0:
        out.append(0)
    elif y_mat[i,0] == 1 and y_mat[i,1] == 0 and y_mat[i,2] == 0 and y_mat[i,3] == 1:
        out.append(1)
    elif y_mat[i,0] == 0 and y_mat[i,1] == 0 and y_mat[i,2] == 1 and y_mat[i,3] == 1:
        out.append(2)
    elif y_mat[i,0] == 1 and y_mat[i,1] == 0 and y_mat[i,2] == 1 and y_mat[i,3] == 1:
        out.append(3)
    elif y_mat[i,0] == 0 and y_mat[i,1] == 1 and y_mat[i,2] == 1 and y_mat[i,3] == 1:
        out.append(4)
    elif y_mat[i,0] == 1 and y_mat[i,1] == 1 and y_mat[i,2] == 1 and y_mat[i,3] == 1:
        out.append(5)
    else:
        out.append(6)
 
y = pd.DataFrame(out,columns=['salida'])       

y.head()

salida
0        1
1        4
2        0
3        1
4        2
..     ...
95       2
96       3
97       4
98       1
99       0

[100 rows x 1 columns]

# Carga de modelos con Scikitlearn
## Joblib - Pickles
### Formato de salida: modelo_entrenado.SAV

In [22]:
import joblib

dir_modelo = 'C:/Users/christianr/Documents/GitHub/EndomorfismoII_2024_2/PROYECTOS/PARCIAL 1/submissions/aguilardelgadoemiliojose_12751_5900126_mejor_arbol_decision.pkl'
modelo = joblib.load(dir_modelo)

c:\Users\christianr\anaconda3\envs\dias\lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.5.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\christianr\anaconda3\envs\dias\lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.5.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\christianr\anaconda3\envs\dias\lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.5.2 when u

AttributeError: Can't get attribute '_Scorer' on <module 'sklearn.metrics._scorer' from 'c:\\Users\\christianr\\anaconda3\\envs\\dias\\lib\\site-packages\\sklearn\\metrics\\_scorer.py'>

In [26]:
import pickle

dir_modelo = 'C:/Users/christianr/Documents/GitHub/EndomorfismoII_2024_2/PROYECTOS/PARCIAL 1/submissions/albanterangabrielarturo/AlbanArroyoProyectoEndo/best_model.pkl'
with open (dir_modelo, "rb") as f:
    modelo = pickle.load(f)


c:\Users\christianr\anaconda3\envs\dias\lib\site-packages\sklearn\base.py:347: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 1.5.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


UnpicklingError: invalid load key, '\x0f'.

In [24]:
# Predecir con el modelo
y_pred = modelo.predict(X) 

from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y, y_pred)

print(f'La exactitud del modelo entrenado es: {exactitud}')


AttributeError: 'numpy.ndarray' object has no attribute 'predict'